#!/bin/bash

# Control script to start/stop ruby/rack redis job on a BOSH controlled VM
#
# In local development, this script can be run manually. Examples below assume you are in the root of this release project.
#
# Start process example:
# APP_DIR=/path/to/redis RACK_ENV=development COMMAND=shotgun PORT=9393 jobs/redis/templates/redis_ctl start
#
# View STDOUT/STDERR logs:
# jobs/redis/templates/redis_ctl logs
#
# Clear logs:
# jobs/redis/templates/redis_ctl clearlogs

# TODO - change "EXECUTABLE_SERVER" to the command to run

RUN_DIR=/var/vcap/sys/run/redis
LOG_DIR=/var/vcap/sys/log/redis
STORE=/var/vcap/store/redis
PIDFILE=$RUN_DIR/redis.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH

COMMAND=${COMMAND:-/var/vcap/packages/redis/bin/redis-server /var/vcap/jobs/redis/config/redis.conf}
HOME=${HOME:-/home/vcap}

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    echo $$ > $PIDFILE

    exec $COMMAND >>$LOG_DIR/redis.stdout.log 2>>$LOG_DIR/redis.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: redis_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
